CREATE TABLE library.users
(
user_id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
nickname VARCHAR(30) NOT NULL UNIQUE,
password VARCHAR(30),
email VARCHAR(30) NOT NULL UNIQUE,
);
CREATE TABLE library.postbook (
post_id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
user_id INT NOT NULL,
text VARCHAR(512),
post_date DATETIME NOT NULL,
book LONGBLOB,
FOREIGN KEY (user_id) REFERENCES users (user_id) ON UPDATE CASCADE ON DELETE CASCADE
);
CREATE TABLE library.comment
(
comment_id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
post_id INT NOT NULL,
user_id INT NOT NULL,
text VARCHAR
comment_date DATETIME NOT NULL,
FOREIGN KEY (user_id) REFERENCES users (user_id) ON UPDATE CASCADE ON DELETE CASCADE,
FOREIGN KEY (post_id) REFERENCES postbook (post_id) ON UPDATE CASCADE ON DELETE CASCADE
);